### ISSUE TITLE
mpl lab

### ISSUE THREAD

**Issue by Sageblatt** [ZaytsevAlexandr/PythonLabs#1]
Пока что могу поставить хор7: есть небольшая ошибка:
В тексте первого пункта лабы было требование 2 (про корректную передачу соотношения сторон рассматриваемой области). Нужно его всё же выполнить.

Небольшие замечания:
1) Убирать символ конца строки с помощью среза -- плохая практика (конец строки может быть и не одним символом, например, CRLF). https://github.com/ZaytsevAlexandr/PytonLabs/blob/7363a65d6d84836ecd98bd4290c284e8aa21cfe5/matplotlib/task_1/main.py#L5 Более правильным будет использование `string.rstrip()`.
2) Тут https://github.com/ZaytsevAlexandr/PytonLabs/blob/7363a65d6d84836ecd98bd4290c284e8aa21cfe5/matplotlib/task_1/main.py#L6-L7 не очень понятно, зачем нужны именно np массивы, если их функционал далее не использовался.
3) Чтобы не запускать скрипт несколько раз с разными названиями файлов, можно было задать цикл по названиям файлов  и запускать скрипт единожды. https://github.com/ZaytsevAlexandr/PytonLabs/blob/7363a65d6d84836ecd98bd4290c284e8aa21cfe5/matplotlib/task_1/main.py#L4
4) Импортировать стандартный модуль `math` через одну букву можно в рамках небольшого скрипта, но желательно так не делать при разработке более объёмных программ (учитывая, что названия модуля и так довольно короткое). https://github.com/ZaytsevAlexandr/PytonLabs/blob/7363a65d6d84836ecd98bd4290c284e8aa21cfe5/matplotlib/task_2/main.py#L3
5) Не очень понятно, зачем два раза открывать один и тот же файл. https://github.com/ZaytsevAlexandr/PytonLabs/blob/7363a65d6d84836ecd98bd4290c284e8aa21cfe5/matplotlib/task_2/main.py#L26 (К тому же, во второй раз он не был закрыт).
6) В последнем пункте цветовая палитра подобрана не самым удачным образом: оценки 6 и 7 с трудом различимы на гистограммах.

На итоговую оценку повлияло и это: https://github.com/KuimovDanila/pythonlabs/tree/main/matplotlib.

**Comment by ZaytsevAlexandr** [comment]
Понял.
