### ISSUE TITLE
numpy lab

### ISSUE THREAD

**Issue by Sageblatt** [ZaytsevAlexandr/PythonLabs#3]
Пока что могу поставить 3 балла.
Надо поправить:
1) Тут https://github.com/ZaytsevAlexandr/PythonLabs/blob/dd6a89700a1d3c316ea9307321c326591a7a3f85/numpy/task_1/main.py#L9-L11 можно и нужно вместо цикла использовать операцию над `numpy` массивом
2) Тут https://github.com/ZaytsevAlexandr/PythonLabs/blob/dd6a89700a1d3c316ea9307321c326591a7a3f85/numpy/task_2/main.py#L13-L17 алгоритм по сути правильный, но опять-таки нужно его уместить в рамки `numpy` операций, без циклов.
3) Вместо самодельной функции https://github.com/ZaytsevAlexandr/PythonLabs/blob/dd6a89700a1d3c316ea9307321c326591a7a3f85/numpy/task_2/main.py#L4-L9 следовало бы использовать `np.loadtxt()`.
4) Аналогично п.3 https://github.com/ZaytsevAlexandr/PythonLabs/blob/dd6a89700a1d3c316ea9307321c326591a7a3f85/numpy/task_3/main.py#L6-L12

Замечание:
В третьем пункте вместо сохранения-загрузки картинки во временный файл можно было использовать `matplotlib.animation.FuncAnimation` ([документация тут](https://matplotlib.org/stable/users/explain/animations/animations.html)).

**Comment by ZaytsevAlexandr** [comment]
Подправил
